[tool.poetry]
name = "agribee-telegram-bridge"
version = "0.1.0"
description = ""
authors = ["Gunjan"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "2.3.2"
python-telegram-bot = "20.7"
requests = "2.31.0"

[tool.poetry.dev-dependencies]
